### PR TITLE
adds cross-platform global hotkeys, fixes build in linux

### PR DESCRIPTION
**Pull request by antvconst**
Добавил модифицированный QxtGlobalShortcut, теперь собирается и работает и в линуксе

### CODE REVIEW

**Comment by tucnak** [comment]
[I am not developer, just walking around]

I wouldn't like to have this in codebase. I mean, using Qxt is quite good, but as shared library. Yet, they are experiencing kinda problems with porting it forward to Qt.

Implementing global shortcuts for Linux and Mac OS X is not an issue, but this code is quite good as temporary solution.

**Comment by antvconst** [comment]
Well, it's not that hard to port it yourself as couple of files, isn't it? In my experience, this library parts are working very good under both Windows and Linux.
This files were taken from libqxt's git trunk.

**Comment by bakwc** [comment]
I suggest another alternative, UGlobalHotkeys - a little hotkeys bicycle for Qt5 https://github.com/kciray8/codepaster/pull/3

**Comment by tucnak** [comment]
Going to join @bakwc in his opinion. Having few files from external library is not great at least, because they are created to be executed inside that library. In other words: не стоит юзать файлики либы за ее пределами, так как это как минимум не эстетично.

**Pull request closed without merging**
